sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t jayem1385/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true jayem1385/docker-react npm run test 
