sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t jimmi13/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true jimmi13/docker-react npm run test --coverage 
